### ISSUE TITLE
Installation of "adafruit:samd" blocked by dependency on bossa(c) 1.8 (not available for the current OS)

### ISSUE THREAD

**Issue by jakimfett** [adafruit/arduino-board-index#95] opened 2022-01-17 18:39 UTC
Found a defect in the package definition while attempting installation of the "adafruit:samd" core:
`Error during install: tool arduino:bossac@1.8.0-48-gb176eee not available for the current OS`

- Arduino board:  Adafruit Feather M0 (RFM96 LoRa Radio)

- Arduino IDE version:  n/a (using `arduino-cli` at v0.18.1)

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

1) Start with a clean NixOS v21.11 install atop the Raspberry Pi 4B (4GB version) _(or equivalent `aarch64` system architecture)_.
2) Execute `nix-shell -p arduino-cli`, then `arduino-cli config init`
3) Add the applicable URL to the 'additional_urls' section of the 'board_manager' section in your newly created `~/.arduino15/arduino-cli.yaml` file:
`https://adafruit.github.io/arduino-board-index/package_adafruit_index.json`  
4) Execute `arduino-cli core update-index` (possibly unnecessary step)

_(At this point, the test environment is ready to reproduce the defect, this next step is what failed on my system.)_
---
5) Finally, run the command to install the necessary core for the Feather M0:
`arduino-cli core install adafruit:samd`

```
[shell:~/dev/feather]$ arduino-cli core install adafruit:samd
Downloading packages...
adafruit:arm-none-eabi-gcc@9-2019q4 already downloaded
arduino:bossac@1.7.0-arduino3 already downloaded
Error during install: tool arduino:bossac@1.8.0-48-gb176eee not available for the current OS
``` 

What this message did not tell me is how to resolve the problem myself. It did however inform me of the existence of a 1.7 version of the bossac library, which was correlated by my bug report / query with the Arduino repositories. That conversation led me here.

Huge thanks to @per1234 for [confirming some root causes and identifying several paths forward](https://github.com/arduino/arduino-cli/issues/1626#issuecomment-1014197539) in their exceptionally informational response to my initial attempt at reporting this defect.

---

As I said on the Arduino side, I'm more than happy to contribute to the solution on this...the observation that there's confusion for other users regarding who to talk to about this sort of issue (and even where to resolve it) are ongoing conversations.

**Comment by hathach** [comment] 2022-01-20 15:03
Thank you for reporting the issue, seem like bossac18 binary is not available on AARCH64. I am currently off until weekend, we will fix it in the next week or so. Will post update here when there is one.

**Comment by jakimfett** [comment] 2022-01-21 18:24
Take your time, and thank you for your willingness to remediate this.

(I was attempting to make a local repo with a viable 1.8. but have not progressed past getting it to compile on my test system)

**Comment by jakimfett** [comment] 2022-01-21 18:24
(inadvertently closed the issue, whoops!)

**Comment by hathach** [comment] 2022-01-25 11:04
I just checked, that arduino package does have pre-built binaries for bossac 1.9.1 which seem to work fine with existing upload parameter. I will do more test to see if upgrading from bossac 1.8 to 1.9 is smooth enough.

**Comment by hathach** [comment] 2022-01-27 05:33
this issue should be fixed now since we migrate to bossac 1.9. Please try to install samd 1.7.8 to see if that works for you.

**Comment by jakimfett** [comment] 2022-02-01 02:15
Success!  


![arduino_cli_adafruit_samd_success_DSCF2048_rescaled_cropped](https://user-images.githubusercontent.com/2565176/151903570-edc033cc-6452-4b78-a492-2f2f0f2ae15d.jpg)

Thank you for resolving this issue, much appreciate!

**Comment by hathach** [comment] 2022-02-05 18:21
re-opened since bossac 1.9 has some compatible issue with macos, and we decide to revert back to bossac 1.8 with bsp 1.7.9. Please continue to use 1.7.8 until we figure out the root cause.

- https://forums.adafruit.com/viewtopic.php?f=19&t=187831
- https://forums.adafruit.com/viewtopic.php?f=57&t=187924

**Comment by jakimfett** [comment] 2022-02-05 19:38
> ...continue to use 1.7.8 until we figure out the root cause.

Will do, thank you keeping me informed!

**Comment by hathach** [comment] 2022-02-06 06:04
@jakimfett the issue seems to be https://github.com/shumatech/BOSSA/pull/150 , pr is 1 year old, I don’t know when it got fixed and we cannot upgrade until then. I will try to come up with some tutorial steps for aarch64 user to manually install the tool so that you could continue to use the latest code.

**Closed as completed** 2022-02-18 03:12 UTC
